// Mock API data with Indian mentors
// This can be used with MockAPI.io or similar services

const publicImages = [
  '/cheerful-indian-businessman-smiling-closeup-portrait-jobs-career-campaign.jpg',
  '/cheerful-indian-man.jpg',
  '/close-up-excited-person-portrait.jpg',
  '/happy-brunette-woman-confident-with-natural-hair-feeling-satisfied.jpg',
  '/medium-shot-smiley-man-posing.jpg',
  '/pleased-young-brunette-caucasian-woman-stands-sideways-with-crossed-arms.jpg',
  '/portrait-young-indian-businessman-student-sitting-with-pen.jpg',
  '/portrait-young-stylish-indian-man-model-isolated-pink-wall-background.jpg',
  '/smiling-young-beautiful-girl-looking-straight-ahead-wearing-white-t-shirt-isolated-pink.jpg',
  '/smiling-young-brunette-caucasian-girl-looks-camera-olive-green.jpg',
];

export const INDIAN_MENTORS_MOCK_DATA = [
  {
    id: "1",
    name: "Rajesh Kumar",
    title: "Senior Full Stack Developer",
    companies: "TCS, Infosys",
    experience: "10+ years",
    bio: "Helping aspiring developers master web technologies and build scalable applications. Based in Bangalore.",
    tags: ["JavaScript", "React", "Node.js", "MongoDB", "Web Development"],
    rating: 4.9,
    ratedCount: 156,
    price: 40,
    priceUnit: "Per Min",
    image: publicImages[0],
    isOnline: true
  },
  {
    id: "2",
    name: "Priya Sharma",
    title: "Product Manager",
    companies: "Flipkart, Amazon",
    experience: "9+ years",
    bio: "Specializing in product strategy and user research for e-commerce platforms. Mumbai-based.",
    tags: ["Product Strategy", "User Research", "Analytics", "Leadership"],
    rating: 4.8,
    ratedCount: 142,
    price: 50,
    priceUnit: "Per Min",
    image: publicImages[1],
    isOnline: true
  },
  {
    id: "3",
    name: "Arjun Patel",
    title: "Data Scientist",
    companies: "Flipkart, Swiggy",
    experience: "8+ years",
    bio: "Expert in machine learning and data analytics for business intelligence. Hyderabad-based.",
    tags: ["Python", "Machine Learning", "Data Analysis", "SQL", "TensorFlow"],
    rating: 4.9,
    ratedCount: 128,
    price: 45,
    priceUnit: "Per Min",
    image: publicImages[2],
    isOnline: false
  },
  {
    id: "4",
    name: "Neha Gupta",
    title: "UX/UI Designer",
    companies: "Myntra, Nykaa",
    experience: "7+ years",
    bio: "Specializing in design systems and user-centered design for mobile apps. Delhi-based.",
    tags: ["UI Design", "UX Research", "Figma", "Design Systems", "Mobile Design"],
    rating: 4.7,
    ratedCount: 98,
    price: 35,
    priceUnit: "Per Min",
    image: publicImages[3],
    isOnline: true
  },
  {
    id: "5",
    name: "Vikram Singh",
    title: "DevOps Engineer",
    companies: "Paytm, Razorpay",
    experience: "11+ years",
    bio: "Building robust CI/CD pipelines and cloud infrastructure for fintech. Gurgaon-based.",
    tags: ["AWS", "Docker", "Kubernetes", "CI/CD", "Linux"],
    rating: 4.8,
    ratedCount: 112,
    price: 48,
    priceUnit: "Per Min",
    image: publicImages[4],
    isOnline: true
  },
  {
    id: "6",
    name: "Anjali Verma",
    title: "Mobile App Developer",
    companies: "OYO, Zomato",
    experience: "8+ years",
    bio: "Specialized in React Native and iOS development for consumer apps. Pune-based.",
    tags: ["React Native", "iOS", "Android", "Mobile Development", "Firebase"],
    rating: 4.7,
    ratedCount: 105,
    price: 42,
    priceUnit: "Per Min",
    image: publicImages[5],
    isOnline: false
  },
  {
    id: "7",
    name: "Rohan Desai",
    title: "Backend Engineer",
    companies: "Uber, Ola",
    experience: "9+ years",
    bio: "Expert in building high-performance backend systems and APIs. Bangalore-based.",
    tags: ["Java", "Spring Boot", "Microservices", "PostgreSQL", "Redis"],
    rating: 4.9,
    ratedCount: 134,
    price: 46,
    priceUnit: "Per Min",
    image: publicImages[6],
    isOnline: true
  },
  {
    id: "8",
    name: "Divya Nair",
    title: "Frontend Developer",
    companies: "Accenture, Cognizant",
    experience: "6+ years",
    bio: "Passionate about creating beautiful and responsive web interfaces. Kochi-based.",
    tags: ["React", "Vue.js", "CSS", "TypeScript", "Web Performance"],
    rating: 4.6,
    ratedCount: 87,
    price: 38,
    priceUnit: "Per Min",
    image: publicImages[7],
    isOnline: true
  },
  {
    id: "9",
    name: "Sanjay Reddy",
    title: "Cloud Architect",
    companies: "Microsoft, Google Cloud",
    experience: "12+ years",
    bio: "Designing scalable cloud solutions for enterprise clients. Hyderabad-based.",
    tags: ["AWS", "Azure", "GCP", "Cloud Architecture", "Infrastructure"],
    rating: 4.8,
    ratedCount: 119,
    price: 55,
    priceUnit: "Per Min",
    image: publicImages[8],
    isOnline: false
  },
  {
    id: "10",
    name: "Meera Kapoor",
    title: "QA Engineer",
    companies: "HCL, Tech Mahindra",
    experience: "7+ years",
    bio: "Expert in automation testing and quality assurance strategies. Noida-based.",
    tags: ["Selenium", "Automation Testing", "Python", "Test Management", "CI/CD"],
    rating: 4.7,
    ratedCount: 92,
    price: 35,
    priceUnit: "Per Min",
    image: publicImages[9],
    isOnline: true
  }
];

// Export for easy use
export default INDIAN_MENTORS_MOCK_DATA;
